development:
  adapter: sqlite3
  database: db/surveys
  timeout: 5000

test:
    adapter: postgresql
    database: surveys
    username: vagrant
    host: localhost

production:
    adapter: postgresql
    database: app-dev
    username: user
    host: localhost